import { Geist, Geist_Mono, Lato, Manrope } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "react-hot-toast";
import { ValuesProvider } from "@/context/valuesContext";

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="overflow-x-hidden"
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} ${manrope.variable} antialiased overflow-x-hidden`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <Toaster
            position="bottom-right"
            reverseOrder={false}
            toastOptions={{
              duration: 4000,
              style: {
                background: '#fff',
                color: '#1a1a1a',
                padding: '16px 24px',
                borderRadius: '1.25rem',
                fontSize: '14px',
                fontWeight: '600',
                boxShadow: '0 20px 40px -10px rgba(0,0,0,0.1)',
                border: '1px solid #f3f4f6',
              },
              success: {
                iconTheme: {
                  primary: '#84cc16',
                  secondary: '#fff',
                },
              },
              error: {
                iconTheme: {
                  primary: '#ef4444',
                  secondary: '#fff',
                },
              },
            }}
          />
          <Navbar />
          <ValuesProvider>
            {children}
          </ValuesProvider>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
